services:
  class-app:
    build: .
    container_name: class-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=class
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    networks:
      - class-mysql-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: class
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - class-mysql-network

volumes:
  mysql-data:

networks:
  class-mysql-network:
    driver: bridge
